### PR TITLE
Ember 2 Compatibility

### PR DESCRIPTION
**Pull request by rpatterson**
Make compatible with the Ember 2 way of things.  These changes have been working for us for some months now.

### CODE REVIEW

**Comment by rpatterson** [comment]
Fixed the Travis CI errors

**Comment by Wildhoney** [comment]
Thanks @rpatterson &mdash; really appreciated!

**Comment by rpatterson** [comment]
Thank you!  If you think of it, can you let me know when this is released so we can switch back to a release from the submodule we're using currently.

**Comment by Wildhoney** [comment]
I released it `v0.8.0` 👍

**Pull request merged**
