### PR TITLE
use Ember.run.bind instead of .bind(this)

### PR DESCRIPTION
**Pull request by jorgedavila25**

### CODE REVIEW

**Comment by fsmanuel** [comment]
@jorgedavila25 I guess `Ember.run.bind` would be better than `$.proxy`. Does `$.proxy` help you with the stubbing?

**Comment by Wildhoney** [comment]
`Ember.run.bind` +1

**Comment by jorgedavila25** [comment]
@fsmanuel @Wildhoney thanks for the feedback! i've updated the PR

**Comment by Wildhoney** [comment]
Thanks! :+1: All merged &ndash; released as `v0.7.1`.

**Pull request merged**
